# Generated by Django 3.0.8 on 2020-08-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='There is no bio yet!', max_length=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profileimg',
            field=models.ImageField(default='img.jpg', upload_to='images'),
        ),
    ]
