# Generated by Django 3.0.8 on 2020-08-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200810_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profileimg',
            field=models.ImageField(default='img.jpg', upload_to='media'),
        ),
    ]
