# Generated by Django 3.0.8 on 2020-08-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image',
            field=models.ImageField(default='default', upload_to='media/'),
            preserve_default=False,
        ),
    ]
