# Generated by Django 3.0.8 on 2020-08-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
