# Generated by Django 3.0.8 on 2020-08-13 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200813_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
